version: "3"

services:
  scrapyd:
    build: .
    entrypoint: "scrapyd --pidfile= "
    hostname: "scrapyd"
    restart: unless-stopped
    volumes:
      - /www/prd_spider/logs:/app/logs
      - /www/prd_spider/dbs:/app/dbs
      - /www/prd_spider/eggs:/app/eggs
      - /www/prd_spider/ms-playwright:/ms-playwright
    env_file:
      - .env
    depends_on:
      - redis
  scrapydweb:
    build: .
    entrypoint: "scrapydweb"
    hostname: "scrapydweb"
    restart: unless-stopped
    environment:
      - HOST_SCRAPYD=scrapyd
      - PORT_SCRAPYD=6800
      - DATA_PATH=/app/data
      - SCRAPY_PROJECTS_DIR=/app/data/projects
    volumes:
      - /www/prd_spider/data/projects:/app/data/projects
      - /www/prd_spider/logs:/app/logs
      - /www/prd_spider/data:/app/data
    ports:
      - 6799:5000
    env_file:
      - .env
    depends_on:
      - "scrapyd"
  logparser:
    build: .
    entrypoint: "logparser -dir=/app/logs/"
    hostname: "logparser"
    restart: unless-stopped
    volumes:
      - /www/prd_spider/logs:/app/logs
    env_file:
      - .env
  portia:
    image: scrapinghub/portia
    hostname: portia
    restart: unless-stopped
    environment:
      - SCRAPYD_URL=http://scrapyd:6800/
    ports:
      - 9001:9001
      - 9002:9002
    volumes:
      - /www/prd_spider/data/projects:/app/data/projects:rw
    links:
      - "scrapyd"
    env_file:
      - .env
  redis:
    image: bitnami/redis:latest
    hostname: redis
    env_file:
      - .env
    ports:
      - "6389:6379"
    volumes:
      - /www/redis/conf/overrides.d/:/opt/bitnami/redis/mounted-etc/
      - /www/prd_spider/redis_data:/bitnami/redis/data
    restart: unless-stopped
